version: '3.3'
services:
  post_db:
    container_name: reddit-mongodb
    image: mongo:${ver_mongo}
    volumes:
      - post_db:/data/db
    networks:
      back_net: 
        aliases: 
            - post_db
            - comment_db
    environment:
      - ZIPKIN_ENABLED=${ZIPKIN_ENABLED}

  ui:
    # build: ./ui
    container_name: reddit-ui
    image: ${USERNAME}/ui:${ver_ui}
    ports:
      - ${port_ui}:9292/tcp
    networks:
      - front_net
    logging:
      driver: "fluentd"
      options:
        fluentd-address: localhost:24224
        tag: service.ui
    environment:
      - ZIPKIN_ENABLED=${ZIPKIN_ENABLED}

  post:
    # build: ./post-py
    container_name: reddit-post
    image: ${USERNAME}/post:${ver_post}
    networks:
      - back_net
      - front_net
    logging:
      driver: "fluentd"
      options:
        fluentd-address: localhost:24224
        tag: service.post
    environment:
      - ZIPKIN_ENABLED=${ZIPKIN_ENABLED}

  comment:
    # build: ./comment
    container_name: reddit-comment
    image: ${USERNAME}/comment:${ver_comment}
    networks:
      - back_net
      - front_net
    environment:
      - ZIPKIN_ENABLED=${ZIPKIN_ENABLED}

volumes:
  post_db:
  prometheus_data:

networks:
  back_net:
    # driver: bridge
    # ipam: 
    #     driver: default
    #     config: 
    #         - subnet: 10.0.2.0/24
  front_net:
    # driver: bridge
    # ipam: 
    #     driver: default
    #     config: 
    #         - subnet: 10.0.1.0/24
