apiVersion: v1
kind: Secret
metadata:
  name: ui-ingress
type: kubernetes.io/tls
data:
  # the data is abbreviated in this example
  tls.crt: |
    MIIDEzCCAfugAwIBAgIUfl0CZj4m33jVSLWSVRSKNVD2bawwDQYJKoZIhvcNAQEL
    BQAwGTEXMBUGA1UEAwwOODQuMjAxLjE2MS4xNzgwHhcNMjEwNzA5MTQzMzM1WhcN
    MjIwNzA5MTQzMzM1WjAZMRcwFQYDVQQDDA44NC4yMDEuMTYxLjE3ODCCASIwDQYJ
    KoZIhvcNAQEBBQADggEPADCCAQoCggEBAKOWZyOab+RiofPsLBIdMcigEwss6AzJ
    nX601fmm/rPaUuPAtfmUKy8lqf2jWocf9QjyNT8eF6rNh/B2PIyXlXeB7cJdSNLP
    aByOg1zZLAnbnwRp7pFPsxZMgijToKJ/EVcItLNl7Tz5iztaowKv/cNOdhhJJjO8
    vo7yZJp5UKAnLvg13F+iXFbfb+6+OYMvqRZ380B3t2elmzICA1TtgAzYbHkCib7e
    KUVRLUZeupkzrv7rKDPCmtA8rtH2aNXqGskId5vQi+uDosLKik4bPFjLdMxZ47/3
    La27vfWNoxDXcS/BBFXWnX6K+7z+B88YwDSnr/e0TpsOUq+vc5ZaR5MCAwEAAaNT
    MFEwHQYDVR0OBBYEFEYmUmfBjV8g0HZy7AyargLSkHEuMB8GA1UdIwQYMBaAFEYm
    UmfBjV8g0HZy7AyargLSkHEuMA8GA1UdEwEB/wQFMAMBAf8wDQYJKoZIhvcNAQEL
    BQADggEBACVbLqTDPGBKcg/JmNbdVt1H4cAmuXU2EGxMCFMxW1LD70csmqrZ9AZK
    k0iaPkZOQ8S4EofViKIj0thOX8uVN//YlZ/qbvpSs7l9b71gghXaNbfrsZTR/pSI
    MXQD66OqBzAB6jhmpxasaAX9b7jC0VTT7K4Z/YtKRQ9IumChtfB+BjgcrVHp4Yke
    tCUEfTh6AzJvKxXmAnzs3wU7QzQlbDgvJM5RL5bDJJ81OS3aB9ZbJyAGEs6oV6QT
    TT8ouhf/YLrOJJDpqYQraI3HmKwKiMK8Av7vTohxbhLQd/q7P2E7fXpAhLb1sByG
    oXO4IpblBz9tNWI53dH7SreoqsC+Oz0=
  tls.key: |
    MIIEvQIBADANBgkqhkiG9w0BAQEFAASCBKcwggSjAgEAAoIBAQCjlmcjmm/kYqHz
    7CwSHTHIoBMLLOgMyZ1+tNX5pv6z2lLjwLX5lCsvJan9o1qHH/UI8jU/HheqzYfw
    djyMl5V3ge3CXUjSz2gcjoNc2SwJ258Eae6RT7MWTIIo06CifxFXCLSzZe08+Ys7
    WqMCr/3DTnYYSSYzvL6O8mSaeVCgJy74NdxfolxW32/uvjmDL6kWd/NAd7dnpZsy
    AgNU7YAM2Gx5Aom+3ilFUS1GXrqZM67+6ygzwprQPK7R9mjV6hrJCHeb0Ivrg6LC
    yopOGzxYy3TMWeO/9y2tu731jaMQ13EvwQRV1p1+ivu8/gfPGMA0p6/3tE6bDlKv
    r3OWWkeTAgMBAAECggEADOrYdBhC057yOOeiRz/k6XmyZ0SBglj9Rb8T0mXcYOlR
    eEiEVhPcIRnxRWT7xgXA/Jbbm4NNzR/zpwo/F770f35T/vAMyxCzoOWj+9XuQ00D
    Tn7q5rCLbKxX7s9fNNWh0eSPGEdpJ1JxKxuqGZE6EY0FiD9mc9lolrMPPJ9tvWea
    W9R8jDGTl5mlYzrclmzuD8Ig+aSgfcZhlpmuiXe+k4WDqGsFnQiMbdHIam/4kio5
    fdYe0pnVxUTrWshwl5Uu1JcgCFnIR4MlZhsdtoQrwQNPThE59+S1H0/jMCk43fEc
    QzbD6LwwLtzlYiZZzF7leA8ox86vpblWJqaXGE95MQKBgQDQfDhbQLHYKqL/MDpd
    5bTZUIzDa1ghhi21JdVrijGBxvYF4RNGJoPu9m8zsSeDAMKJ2fc+oOdztUwJGwjp
    ygPWQJ3HNrMRqC68rwDa/k7RQTD1vzhHgkwQzqxb8gJst+PuOysQJxLD/AZ0y6w6
    YcA2uwVvlug1e7CngV+xcf3ZSQKBgQDI3rARPRv118gKmQFrD1SyWs9Mu8QDL7vm
    ZQ5PtXLtC3UdoXLMq30hNZgB+0y8UCEF4I6RbzTFf5+8PMzHav1ACt4eMRVVZPMB
    ORx0aa0kC9OqkKRao7z4XM8Mh5rLJBIGB/nf04pFsfRDtmpkEqKyyJqkKG3v2G3A
    jU3Xd8lV+wKBgHdswMec7oL6IXZ2hOimnYridk+23LwPZX1f17oLZkKF2wYRIP5N
    L8QhzB9bOlvzgnx+q/9nIk4Iqy6IGvn462u+heLItZjGs0cIJEBN7o41frs2tyFX
    RQVXrinZHoRybhFYOVm+WCSF6Jjc1qJ2vilbxkhetFN2sAGzvUIjHxtpAoGAVLNq
    ROqixqjFxoo8Sdu+GDMopK+seLeBISbNwRi/LGufZ+4zTVCmxAEoZvWDpwiW1Dab
    h4IAG6O0RJjStOhNf9rVTJ/f4hFeUs61S/VfuApwp8S0OTBAN+5StHLd9/juzLJC
    UHqQHNFsMb1S4X3mM0NZygzuRqvZo88x2sC9Gk8CgYEAkfoqc28ea4lPu5aEig71
    bENCn1377xu0nDMCDknBbyXdBNbETcL3TeArCcNrpUXiy4OBUsVEN0GGthE3mjBz
    9VAd31dIbSVmfu64Q+RQ31Gofao8tAhezR86D6OCY89KidHuVbikkHfx0AI2OwYe
    HlrqGI3gc2QBOn4TtwPXtu8=
